[theme]
primaryColor="#ef0707"
backgroundColor="#a9f7e0"
secondaryBackgroundColor="#FFFFFF"
textColor="#0e0e0e"
font = "sans serif"

[global]
dataFrameSerialization = "legacy"




[client]
caching = true
showErrorDetails = true

[server]
fileWatcherType = "auto"
enableXsrfProtection = true
runOnSave = true
maxUploadSize = 200
maxMessageSize = 200




